ibw_affiliate_new:
    path: /new
    defaults: { _controller: IbwJobeetBundle:Affiliate:new }

ibw_affiliate_create:
    path:     /create
    defaults: { _controller: "IbwJobeetBundle:Affiliate:create" }
    requirements: { _method: post|put }
    
ibw_affiliate_wait:
    path: /wait
    defaults: { _controller: IbwJobeetBundle:Affiliate:wait }